name: ExperienceKeepInventory
version: '${version}'
main: at.josias.experiencekeepinventory.ExperienceKeepInventory
api-version: '1.20'
commands:
  xpcheck:
    description: Checks if you have enough XP in case of death to keep the items instead of dropping them
    usage: /<command>