name: ExperienceKeepInventory
version: '${version}'
main: at.josias.experiencekeepinventory.ExperienceKeepInventory
api-version: '1.20'
commands:
  expcheck:
    description: Checks if you have enough EXP in case of death to keep the items instead of dropping them
    usage: /<command>